// Generated by CoffeeScript 1.3.3
(function() {

//  module.exports = {
//    connectId: '606535B47BCB68B9286E',
//    secretKey: 'c061512a567b49+3a1b3d80EDb4a79/012Ace042',
//    adspace: '1615657'
//  };
  module.exports = {
    connectId: '340560B4CB68F85C2376',
    secretKey: 'fC97B2c30A9841+980b086a4C6C23c/3A99Fec42',
    adspace: '1889249'
  };
  
}).call(this);
